# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]

    success_channel:
        class: AppBundle\Services\LoggerService
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: SUCCESS_LOG_CHANNEL }

    error_channel:
        class: AppBundle\Services\LoggerService
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: ERROR_LOG_CHANNEL }

    logging_handler:
        class:  AppBundle\Logger\MonologMySQLWrapper
        arguments: ["@pdo", "logs", [field1, field2, field3]]

    pdo:
        class: Doctrine\DBAL\Driver\PDOConnection
        arguments: ["mysql:dbname=%database_name%", %database_user%, %database_password%]
